### ISSUE TITLE
Unexpected Keyword Argument 'Name'

### ISSUE THREAD

**Issue by Wang-MK** [ShuvamJaswal/Gdrive-Stremio-Update#4]
Receiving the following error when the addon tries to look up an item:

> **[GET] /stream/series/tt3581920%3A1%3A2.json
23:49:27:26
> Reading /tmp/tt3581920.json!Reading /tmp/requests_session.pickle!Saving /tmp/requests_session.pickle!Reading /tmp/requests_session.pickle!Saving /tmp/requests_session.pickle![ERROR] TypeError: set_meta() got an unexpected keyword argument 'name'Traceback (most recent call last):  File "/var/task/vc__handler__python.py", line 166, in vc_handler    if response.data:  File "/var/task/werkzeug/wrappers/response.py", line 314, in get_data    self._ensure_sequence()  File "/var/task/werkzeug/wrappers/response.py", line 376, in _ensure_sequence    self.make_sequence()  File "/var/task/werkzeug/wrappers/response.py", line 391, in make_sequence    self.response = list(self.iter_encoded())  File "/var/task/werkzeug/wrappers/response.py", line 50, in _iter_encoded    for item in iterable:  File "/var/task/werkzeug/wsgi.py", line 500, in __next__    return self._next()  File "/var/task/werkzeug/wsgi.py", line 500, in __next__    return self._next()  File "/var/task/werkzeug/wrappers/response.py", line 50, in _iter_encoded    for item in iterable:  File "/var/task/sgd/routes.py", line 63, in get_streams    stream_meta = Meta(stream_type, stream_id)  File "/var/task/sgd/meta.py", line 120, in __init__    IMDb.__init__(self)  File "/var/task/sgd/meta.py", line 21, in __init__    if not self.get_meta_from_imdb_sg():  File "/var/task/sgd/meta.py", line 85, in get_meta_from_imdb_sg    self.set_meta(meta[0], year="y", name="l")**

**Comment by ShuvamJaswal** [comment]
Hello, for this issue u can try two things
 

1.Goto sgd>meta.py

2. Inside self.get_meta_from_imdb_sg() function
Find line
self.set_meta(meta[0], year="y", name="l")
And in this replace name with title.
self.set_meta(meta[0], year="y", title="l")

Though I don't know how this function scrapes data as I have never really used this.  But I think it will remove that error.

Or u can try other method which IMO is better.

Inside meta.py
Goto constructor (__init__ function) of class IMDb
Goto if conditions
There make the first call to self.get_meta_from_cinemeta()
Instead of self.get_meta_from_imdb_html()

i mean replace
if not self.get_meta_from_imdb_html()
With 
if not self.get_meta_from_cinemeta()

**Comment by Wang-MK** [comment]
Thanks, the first option worked!
